Resources:
  EmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.emailQueue}
      FifoQueue: true
      MessageRetentionPeriod: 86400 # 1 day
      VisibilityTimeout: 900
      ReceiveMessageWaitTimeSeconds: 20
  EmailQueueSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:custom.projectName}-email-queue-url-${self:custom.stage}
      Type: String
      Value: !Ref EmailQueue

Outputs:
  EmailQueueUrl:
    Value: !Ref EmailQueue
    Export:
      Name: EmailQueue-${self:custom.stage}
